### ISSUE TITLE
Cylinder not rendered correctly

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#155]
- Version: 0.1.0
- Name: Frank von Delft
- Description: In the screenshot, that little green disk at the centre of the screen is surely wrong, somehow.  (It does seem to be a separate vector.)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583302230735273162.png?raw=true)

**Comment by boriskovar-m2ms** [comment]
Also target EPB41L3A. Vectors for fragment X0161_1
Upon selecting this outlier it seems that it's the same vector or at least the very same compounds are displayed and same vector label. It seems that it's some kind of weird glitch that needs to be investigated
![image](https://user-images.githubusercontent.com/16878338/75864516-6d01c700-5e02-11ea-98d9-360b2d80a7dd.png)

**Comment by matej-vavrek** [comment]
The little green circle is the lower part of arrow (line). It seems to be a render flaw and it is because of radius of green vectors which is set to 0.8 (so they are bigger), it stops behave like this with radius of 0.5 and for example red vectors have radius of 0.3. We will discuss this and make some adjustments.

**Comment by phraenquex** [comment]
Now in production - thanks!
