### ISSUE TITLE
[Application] Shift + click in Compound on vector to pick is not working

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#260]
When I select molecule to NGL by shift +click, molecule in Compounds on vector to pick has lighter colour (highlighted as picked), but is not displayed in NGL viewer.

**Comment by tibor-postek-m2ms** [comment]
Bug in not caused by our side. It is BE bug
at boris environment (without project implementatiion)
![image](https://user-images.githubusercontent.com/57392303/79719250-71b10a80-82de-11ea-8ce6-87f6c6949fe2.png)
at tibor environment
![image](https://user-images.githubusercontent.com/57392303/79719299-8beae880-82de-11ea-83d1-33b13271351f.png)
