### ISSUE TITLE
Finalise/fix selected compound export

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#423]
Add download as CSV button to Selected Compounds tab (RHS). Should  contain following columns: smiles, data set from where they come from.

Add download as SDF file button to the same tab (Selected Compounds tab RHS) which will contain definition of selected compounds.

**Comment by teriraj** [comment]
The buttons are added, it is possible to download the data to a file. 
I'm not sure if the output in Excel is displayed correctly - because of the description - "Should contain following columns: smiles, data"  that two columns - smiles and data should be displayed. But in Excel, both smiles and data are in one column - separated by a comma.
![image](https://user-images.githubusercontent.com/65952633/99256354-91c58f80-2815-11eb-8f27-4b176f888183.png)

**Comment by reskyner** [comment]
Add selected vector compounds to 'selected compounds' tab & include in selection for download. 

- Compound ID & library ID to be added when available (vector network)
- Spec for sdf/csv to be defined
- How to display vector compounds in same list
- Needs to be captured as an action

**Comment by phraenquex** [comment]
After a further brainstorm:
* the _real_ requirement is that SDF needs to be extendable in future
* it should therefore be assembled by the backend
* it will require implementing backend functionality that the frontend can call with the necessary parameters to tell the backend what needs assembling.  Presumably includes a list of compound_ids 
* (probably) the front will need to be passed the compound_id fields from the backend
Sounded like @duncanpeacock would have to investigate the json files, and talk to @boriskovar-m2ms to work out the full spec.

@phraenquex adds the request that if the requirements look like exploding the spec, please report back immediately so we can discuss plan B.
