### ISSUE TITLE
To match smiles in fragment network, they should be standardised in the loading step

### ISSUE THREAD

**Issue by reskyner** [m2ms/fragalysis-frontend#579]
In order to ensure we can find the correct molecule in the fragment network, we should standardise molecules in the same way as is done for populating the network. 

This should be added to the loader step before the molecule smiles strings are added to the database.

Relevant code is here: https://github.com/InformaticsMatters/fragmentor/blob/ad1fbdcbf391af0b9c05b1aa76498d059fc6b92d/frag/utils/rdkit_utils.py#L245

**Comment by duncanpeacock** [comment]
Duncan / Rachael discussed this issue after input from Tim.

It was decisied that rather than on the upload, the smiles should be standardized when calling the fragment graph. This is in the api /graph/<id> call.
To check: whether standardizing the smiles on the call will affect the smiles returned - this is a potential complexity.

**Comment by phraenquex** [comment]
Should be part of #652 .  Close this one.
